### ISSUE TITLE
Generated DKIM is too long for a TXT record

### ISSUE THREAD

**Issue by rapmankin** [Angatar/mailman2#8]
I tried to add the generated DKIM key to my DNS setup and got the  error:

The following errors have occurred:-

    The Value cannot be longer than 255 characters.

The generated value appears to be about 400 characters. It is necessary to split the generated key into sections by inserting '**" "**' every so often. Maybe an update to your scripts, or  to the docs, would be in order.

All other things are working fine, thank you (other than that gmail would not accept mails  from sites without a valid DKIM).

**Comment by Angatar** [comment]
The container self-generates a 2048 bits DKIM key which is becoming the new standard that should be accepted in most cases.

If your DNS TXT records are limited to 255 characters you can indeed try to split the string into a single record.  There are online **DNS record splitter services** dedicated to that purpose that might help you in this task  ;)
If it doesn't work you can contact your domain host to find out whether TXT records with more than 255 characters can be supported.

You can of course also use your own DKIM key by replacing the relevant files in ```/etc/exim4/tls.d/ ``` with a volume (2048 bits key is a best practice than 1024 bits even if longer).

NB: Thx for the feedback! :grin:
